// Code generated by https://github.com/zhufuyi/sponge

package ecode

import (
	"github.com/zhufuyi/sponge/pkg/errcode"
)

// postService http service level error code
var (
	postServiceNO       = 3 // number range 1~100, if there is the same number, trigger panic.
	postServiceName     = "postService"
	postServiceBaseCode = errcode.HCode(postServiceNO)

	ErrCreatePostService         = errcode.NewError(postServiceBaseCode+1, "failed to Create "+postServiceName)
	ErrUpdateContentPostService  = errcode.NewError(postServiceBaseCode+2, "failed to UpdateContent "+postServiceName)
	ErrDeletePostService         = errcode.NewError(postServiceBaseCode+3, "failed to Delete "+postServiceName)
	ErrGetByIDPostService        = errcode.NewError(postServiceBaseCode+4, "failed to GetByID "+postServiceName)
	ErrListByIDsPostService      = errcode.NewError(postServiceBaseCode+5, "failed to ListByIDs "+postServiceName)
	ErrListByUserIDPostService   = errcode.NewError(postServiceBaseCode+6, "failed to ListByUserID "+postServiceName)
	ErrListLatestPostService     = errcode.NewError(postServiceBaseCode+7, "failed to ListLatest "+postServiceName)
	ErrListHotPostService        = errcode.NewError(postServiceBaseCode+8, "failed to ListHot "+postServiceName)
	ErrIncrViewCountPostService  = errcode.NewError(postServiceBaseCode+9, "failed to IncrViewCount "+postServiceName)
	ErrIncrShareCountPostService = errcode.NewError(postServiceBaseCode+10, "failed to IncrShareCount "+postServiceName)
	ErrPostTypePostService       = errcode.NewError(postServiceBaseCode+11, "发布类型参数错误")
	ErrPostType2PostService      = errcode.NewError(postServiceBaseCode+12, "发布类型中图片和视频只能选其中一个")
	ErrVideoParamPostService     = errcode.NewError(postServiceBaseCode+13, "发布视频参数错误")
	// add +1 to the previous error code
)
