// Code generated by https://github.com/zhufuyi/sponge

package ecode

import (
	"github.com/zhufuyi/sponge/pkg/errcode"
)

// user rpc service level error code
var (
	_userNO       = 8 // number range 1~100, if there is the same number, trigger panic.
	_userName     = "user"
	_userBaseCode = errcode.RCode(_userNO)

	StatusRegisterUser       = errcode.NewRPCStatus(_userBaseCode+1, "failed to Register "+_userName)
	StatusLoginUser          = errcode.NewRPCStatus(_userBaseCode+2, "failed to Login "+_userName)
	StatusLogoutUser         = errcode.NewRPCStatus(_userBaseCode+3, "failed to Logout "+_userName)
	StatusChangePasswordUser = errcode.NewRPCStatus(_userBaseCode+4, "failed to ChangePassword "+_userName)
	// add +1 to the previous error code
)
