// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/shop_gw/v1/shop_gw.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetDetailsByProductIDRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetDetailsByProductIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDetailsByProductIDRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetDetailsByProductIDRequestMultiError, or nil if none found.
func (m *GetDetailsByProductIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDetailsByProductIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetProductID() < 1 {
		err := GetDetailsByProductIDRequestValidationError{
			field:  "ProductID",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetDetailsByProductIDRequestMultiError(errors)
	}

	return nil
}

// GetDetailsByProductIDRequestMultiError is an error wrapping multiple
// validation errors returned by GetDetailsByProductIDRequest.ValidateAll() if
// the designated constraints aren't met.
type GetDetailsByProductIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDetailsByProductIDRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDetailsByProductIDRequestMultiError) AllErrors() []error { return m }

// GetDetailsByProductIDRequestValidationError is the validation error returned
// by GetDetailsByProductIDRequest.Validate if the designated constraints
// aren't met.
type GetDetailsByProductIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDetailsByProductIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDetailsByProductIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDetailsByProductIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDetailsByProductIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDetailsByProductIDRequestValidationError) ErrorName() string {
	return "GetDetailsByProductIDRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetDetailsByProductIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDetailsByProductIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDetailsByProductIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDetailsByProductIDRequestValidationError{}

// Validate checks the field values on GetDetailsByProductIDReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetDetailsByProductIDReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDetailsByProductIDReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetDetailsByProductIDReplyMultiError, or nil if none found.
func (m *GetDetailsByProductIDReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDetailsByProductIDReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetProductDetail()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetDetailsByProductIDReplyValidationError{
					field:  "ProductDetail",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetDetailsByProductIDReplyValidationError{
					field:  "ProductDetail",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProductDetail()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetDetailsByProductIDReplyValidationError{
				field:  "ProductDetail",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetInventoryDetail()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetDetailsByProductIDReplyValidationError{
					field:  "InventoryDetail",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetDetailsByProductIDReplyValidationError{
					field:  "InventoryDetail",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetInventoryDetail()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetDetailsByProductIDReplyValidationError{
				field:  "InventoryDetail",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetCommentDetails() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetDetailsByProductIDReplyValidationError{
						field:  fmt.Sprintf("CommentDetails[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetDetailsByProductIDReplyValidationError{
						field:  fmt.Sprintf("CommentDetails[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetDetailsByProductIDReplyValidationError{
					field:  fmt.Sprintf("CommentDetails[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetDetailsByProductIDReplyMultiError(errors)
	}

	return nil
}

// GetDetailsByProductIDReplyMultiError is an error wrapping multiple
// validation errors returned by GetDetailsByProductIDReply.ValidateAll() if
// the designated constraints aren't met.
type GetDetailsByProductIDReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDetailsByProductIDReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDetailsByProductIDReplyMultiError) AllErrors() []error { return m }

// GetDetailsByProductIDReplyValidationError is the validation error returned
// by GetDetailsByProductIDReply.Validate if the designated constraints aren't met.
type GetDetailsByProductIDReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDetailsByProductIDReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDetailsByProductIDReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDetailsByProductIDReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDetailsByProductIDReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDetailsByProductIDReplyValidationError) ErrorName() string {
	return "GetDetailsByProductIDReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetDetailsByProductIDReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDetailsByProductIDReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDetailsByProductIDReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDetailsByProductIDReplyValidationError{}
