// Code generated by https://github.com/zhufuyi/sponge

package ecode

import (
	"github.com/zhufuyi/sponge/pkg/errcode"
)

// pay business-level rpc error codes.
// the _payNO value range is 1~100, if the same number appears, it will cause a failure to start the service.
var (
	_payNO       = 46
	_payName     = "pay"
	_payBaseCode = errcode.RCode(_payNO)

	StatusCreatePay       = errcode.NewRPCStatus(_payBaseCode+1, "failed to Create "+_payName)
	StatusCreateRevertPay = errcode.NewRPCStatus(_payBaseCode+2, "failed to CreateRevert "+_payName)
	// error codes are globally unique, adding 1 to the previous error code
)
