// Code generated by https://github.com/zhufuyi/sponge

package ecode

import (
	"github.com/zhufuyi/sponge/pkg/errcode"
)

// commentService business-level rpc error codes.
// the _commentServiceNO value range is 1~100, if the same number appears, it will cause a failure to start the service.
var (
	_commentServiceNO       = 89
	_commentServiceName     = "commentService"
	_commentServiceBaseCode = errcode.RCode(_commentServiceNO)

	StatusCreateCommentService     = errcode.NewRPCStatus(_commentServiceBaseCode+1, "failed to Create "+_commentServiceName)
	StatusDeleteByIDCommentService = errcode.NewRPCStatus(_commentServiceBaseCode+2, "failed to DeleteByID "+_commentServiceName)
	StatusUpdateByIDCommentService = errcode.NewRPCStatus(_commentServiceBaseCode+3, "failed to UpdateByID "+_commentServiceName)
	StatusReplyCommentService      = errcode.NewRPCStatus(_commentServiceBaseCode+4, "failed to Reply "+_commentServiceName)
	StatusGetByIDCommentService    = errcode.NewRPCStatus(_commentServiceBaseCode+5, "failed to GetByID "+_commentServiceName)
	StatusListByIDsCommentService  = errcode.NewRPCStatus(_commentServiceBaseCode+6, "failed to ListByIDs "+_commentServiceName)
	StatusListLatestCommentService = errcode.NewRPCStatus(_commentServiceBaseCode+7, "failed to ListLatest "+_commentServiceName)
	StatusListHotCommentService    = errcode.NewRPCStatus(_commentServiceBaseCode+8, "failed to ListHot "+_commentServiceName)
	StatusListReplyCommentService  = errcode.NewRPCStatus(_commentServiceBaseCode+9, "failed to ListReply "+_commentServiceName)
	StatusReCommentService         = errcode.NewRPCStatus(_commentServiceBaseCode+10, "不支持多次嵌套已回复的评论")
	// error codes are globally unique, adding 1 to the previous error code
)
