// Code generated by https://github.com/zhufuyi/sponge

package ecode

import (
	"github.com/zhufuyi/sponge/pkg/errcode"
)

// eShopGw business-level rpc error codes.
// the eShopGwNO value range is 1~100, if the same error code is used, it will cause panic.
var (
	_eShopGwNO       = 75
	_eShopGwName     = "eShopGw"
	_eShopGwBaseCode = errcode.RCode(_eShopGwNO)

	StatusGetDetailsByProductIDEShopGw = errcode.NewRPCStatus(_eShopGwBaseCode+1, "failed to GetDetailsByProductID "+_eShopGwName)

	// error codes are globally unique, adding 1 to the previous error code
)
