// Code generated by https://github.com/zhufuyi/sponge

package ecode

import (
	"github.com/zhufuyi/sponge/pkg/errcode"
)

// stock business-level rpc error codes.
// the _stockNO value range is 1~100, if the same error code is used, it will cause panic.
var (
	_stockNO       = 82
	_stockName     = "stock"
	_stockBaseCode = errcode.RCode(_stockNO)

	StatusCreateStock     = errcode.NewRPCStatus(_stockBaseCode+1, "failed to Create "+_stockName)
	StatusDeleteByIDStock = errcode.NewRPCStatus(_stockBaseCode+2, "failed to DeleteByID "+_stockName)
	StatusUpdateByIDStock = errcode.NewRPCStatus(_stockBaseCode+3, "failed to UpdateByID "+_stockName)
	StatusGetByIDStock    = errcode.NewRPCStatus(_stockBaseCode+4, "failed to GetByID "+_stockName)
	StatusListStock       = errcode.NewRPCStatus(_stockBaseCode+5, "failed to List "+_stockName)

	// error codes are globally unique, adding 1 to the previous error code
)
