// Code generated by https://github.com/zhufuyi/sponge

package routers

import (
	"context"

	user_gwV1 "user_gw/api/user_gw/v1"
	"user_gw/internal/service"

	"github.com/zhufuyi/sponge/pkg/gin/middleware"
	"github.com/zhufuyi/sponge/pkg/logger"

	"github.com/gin-gonic/gin"
	"google.golang.org/grpc/metadata"
)

func init() {
	allMiddlewareFns = append(allMiddlewareFns, func(c *middlewareConfig) {
		userMiddlewares(c)
	})

	allRouteFns = append(allRouteFns,
		func(r *gin.Engine, groupPathMiddlewares map[string][]gin.HandlerFunc, singlePathMiddlewares map[string][]gin.HandlerFunc) {
			userRouter(r, groupPathMiddlewares, singlePathMiddlewares, service.NewUserClient())
		})
}

func userRouter(
	r *gin.Engine,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iService user_gwV1.UserLogicer) {
	ctxFn := func(c *gin.Context) context.Context {
		md := metadata.New(map[string]string{
			// set metadata to be passed from http to rpc
			middleware.ContextRequestIDKey: middleware.GCtxRequestID(c), // request_id
			//middleware.HeaderAuthorizationKey: c.GetHeader(middleware.HeaderAuthorizationKey),  // authorization
		})
		return metadata.NewOutgoingContext(c, md)
	}

	user_gwV1.RegisterUserRouter(
		r,
		groupPathMiddlewares,
		singlePathMiddlewares,
		iService,
		user_gwV1.WithUserRPCResponse(),
		user_gwV1.WithUserLogger(logger.Get()),
		user_gwV1.WithUserRPCStatusToHTTPCode(
		// Set some error codes to standard http return codes,
		// by default there is already ecode.StatusInternalServerError and ecode.StatusServiceUnavailable
		// example:
		// 	ecode.StatusUnimplemented, ecode.StatusAborted,
		),
		user_gwV1.WithUserWrapCtx(ctxFn),
	)
}

// you can set the middleware of a route group, or set the middleware of a single route,
// or you can mix them, pay attention to the duplication of middleware when mixing them,
// it is recommended to set the middleware of a single route in preference
func userMiddlewares(c *middlewareConfig) {
	// set up group route middleware, group path is left prefix rules,
	// if the left prefix is hit, the middleware will take effect, e.g. group route is /api/v1, route /api/v1/user/:id  will take effect
	// c.setGroupPath("/api/v1/user", middleware.Auth())

	// set up single route middleware, just uncomment the code and fill in the middlewares, nothing else needs to be changed
	//c.setSinglePath("POST", "/api/v1/user/register", middleware.Auth())
	//c.setSinglePath("POST", "/api/v1/user/login", middleware.Auth())
	c.setSinglePath("POST", "/api/v1/user/logout", middleware.Auth())
	c.setSinglePath("POST", "/api/v1/user/change_password", middleware.Auth())
}
