// Code generated by https://github.com/zhufuyi/sponge

package routers

import (
	communityV1 "community/api/community/v1"
	"community/internal/handler"

	"github.com/zhufuyi/sponge/pkg/gin/middleware"
	"github.com/zhufuyi/sponge/pkg/logger"

	"github.com/gin-gonic/gin"
)

func init() {
	allMiddlewareFns = append(allMiddlewareFns, func(c *middlewareConfig) {
		relationServiceMiddlewares(c)
	})

	allRouteFns = append(allRouteFns,
		func(r *gin.Engine, groupPathMiddlewares map[string][]gin.HandlerFunc, singlePathMiddlewares map[string][]gin.HandlerFunc) {
			relationServiceRouter(r, groupPathMiddlewares, singlePathMiddlewares, handler.NewRelationServiceHandler())
		})
}

func relationServiceRouter(
	r *gin.Engine,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iService communityV1.RelationServiceLogicer) {
	communityV1.RegisterRelationServiceRouter(
		r,
		groupPathMiddlewares,
		singlePathMiddlewares,
		iService,
		communityV1.WithRelationServiceHTTPResponse(),
		communityV1.WithRelationServiceLogger(logger.Get()),
		communityV1.WithRelationServiceErrorToHTTPCode(
		// Set some error codes to standard http return codes,
		// by default there is already ecode.InternalServerError and ecode.ServiceUnavailable
		// example:
		// 	ecode.Forbidden, ecode.LimitExceed,
		),
	)
}

// you can set the middleware of a route group, or set the middleware of a single route,
// or you can mix them, pay attention to the duplication of middleware when mixing them,
// it is recommended to set the middleware of a single route in preference
func relationServiceMiddlewares(c *middlewareConfig) {
	// set up group route middleware, group path is left prefix rules,
	// if the left prefix is hit, the middleware will take effect, e.g. group route is /api/v1, route /api/v1/relationService/:id  will take effect
	c.setGroupPath("/api/v1/relation", middleware.Auth(middleware.WithVerify(verify)))

	// set up single route middleware, just uncomment the code and fill in the middlewares, nothing else needs to be changed
	//c.setSinglePath("POST", "/api/v1/relation/follow", middleware.Auth())
	//c.setSinglePath("POST", "/api/v1/relation/unfollow", middleware.Auth())
	//c.setSinglePath("GET", "/api/v1/relation/following/list", middleware.Auth())
	//c.setSinglePath("GET", "/api/v1/relation/follower/list", middleware.Auth())
	//c.setSinglePath("POST", "/api/v1/relation/check/list", middleware.Auth())
}
