// Code generated by https://github.com/zhufuyi/sponge

package handler

import (
	"context"

	userV1 "eshop/api/user/v1"
	"eshop/user/internal/service"
)

var _ userV1.UserLogicer = (*userHandler)(nil)

type userHandler struct {
	server userV1.UserServer
}

// NewUserHandler create a handler
func NewUserHandler() userV1.UserLogicer {
	return &userHandler{
		server: service.NewUserServer(),
	}
}

// Create user
func (h *userHandler) Create(ctx context.Context, req *userV1.CreateUserRequest) (*userV1.CreateUserReply, error) {

	return h.server.Create(ctx, req)
}

// DeleteByID delete user by id
func (h *userHandler) DeleteByID(ctx context.Context, req *userV1.DeleteUserByIDRequest) (*userV1.DeleteUserByIDReply, error) {

	return h.server.DeleteByID(ctx, req)
}

// UpdateByID update user by id
func (h *userHandler) UpdateByID(ctx context.Context, req *userV1.UpdateUserByIDRequest) (*userV1.UpdateUserByIDReply, error) {

	return h.server.UpdateByID(ctx, req)
}

// GetByID get user by id
func (h *userHandler) GetByID(ctx context.Context, req *userV1.GetUserByIDRequest) (*userV1.GetUserByIDReply, error) {

	return h.server.GetByID(ctx, req)
}

// List of user by query parameters
func (h *userHandler) List(ctx context.Context, req *userV1.ListUserRequest) (*userV1.ListUserReply, error) {

	return h.server.List(ctx, req)
}
