// Code generated by https://github.com/zhufuyi/sponge

package handler

import (
	"context"
	"errors"

	communityV1 "community/api/community/v1"
	"community/internal/cache"
	"community/internal/dao"
	"community/internal/ecode"
	"community/internal/model"

	"github.com/zhufuyi/sponge/pkg/gin/middleware"
	"github.com/zhufuyi/sponge/pkg/logger"
	"github.com/zhufuyi/sponge/pkg/mysql"
	"github.com/zhufuyi/sponge/pkg/mysql/query"

	"github.com/gin-gonic/gin"
)

const (
	// 关注状态
	followStatusDone = 1 // 已关注
	followStatusNot  = 0 // 未关注
)

var _ communityV1.RelationServiceLogicer = (*relationServiceHandler)(nil)

type relationServiceHandler struct {
	userFollowerDao  dao.UserFollowerDao
	userFollowingDao dao.UserFollowingDao
	relationNumDao   dao.RelationNumDao
}

// NewRelationServiceHandler create a handler
func NewRelationServiceHandler() communityV1.RelationServiceLogicer {
	return &relationServiceHandler{
		userFollowerDao: dao.NewUserFollowerDao(
			model.GetDB(),
			cache.NewUserFollowerCache(model.GetCacheType()),
		),
		userFollowingDao: dao.NewUserFollowingDao(
			model.GetDB(),
			cache.NewUserFollowingCache(model.GetCacheType()),
		),
		relationNumDao: dao.NewRelationNumDao(
			model.GetDB(),
			cache.NewRelationNumCache(model.GetCacheType()),
		),
	}
}

// Follow 关注
func (h *relationServiceHandler) Follow(ctx context.Context, req *communityV1.FollowRequest) (*communityV1.FollowReply, error) {
	c := ctx.(*gin.Context)
	err := req.Validate()
	if err != nil {
		logger.Warn("req.Validate error", logger.Err(err), logger.Any("req", req), middleware.GCtxRequestIDField(c))
		return nil, ecode.InvalidParams.Err()
	}

	// 判断是否关注了自己
	if req.UserId == req.FollowedUid {
		logger.Warn("can not follow yourself", logger.Any("req", req), middleware.GCtxRequestIDField(c))
		return nil, ecode.ErrFollowSelfRelationService.Err()
	}

	// 判断是否已经关注过了
	userFollowing, err := h.userFollowingDao.GetRelation(ctx, req.UserId, req.FollowedUid)
	if err != nil && !errors.Is(err, model.ErrRecordNotFound) {
		logger.Warn("h.userFollowingDao.GetRelation error", logger.Err(err), logger.Any("req", req), middleware.GCtxRequestIDField(c))
		return nil, ecode.InternalServerError.Err()
	}
	if userFollowing.Status == followStatusDone {
		return &communityV1.FollowReply{}, nil
	}

	db := model.GetDB()
	tx := db.Begin()
	if tx.Error != nil {
		logger.Error("tx error", logger.Err(err), middleware.GCtxRequestIDField(c))
		return nil, ecode.InternalServerError.Err()
	}
	defer func() {
		if r := recover(); r != nil {
			tx.Rollback()
		}
	}()

	// 添加关注
	err = h.userFollowingDao.CreateByTx(ctx, tx, &model.UserFollowing{
		Model:       mysql.Model{ID: userFollowing.ID},
		UserID:      req.UserId,
		FollowedUid: req.FollowedUid,
		Status:      followStatusDone,
	})
	if err != nil {
		tx.Rollback()
		logger.Error("h.userFollowingDao.CreateByTx error", logger.Err(err), logger.Any("req", req), middleware.GCtxRequestIDField(c))
		return nil, ecode.InternalServerError.Err()
	}

	// 添加粉丝
	userFollower, _ := h.userFollowerDao.GetRelation(ctx, req.FollowedUid, req.UserId)
	err = h.userFollowerDao.CreateByTx(ctx, tx, &model.UserFollower{
		Model:       mysql.Model{ID: userFollower.ID},
		UserID:      req.FollowedUid,
		FollowerUid: req.UserId,
		Status:      followStatusDone,
	})
	if err != nil {
		tx.Rollback()
		logger.Error("h.userFollowingDao.CreateByTx error", logger.Err(err), logger.Any("req", req), middleware.GCtxRequestIDField(c))
		return nil, ecode.InternalServerError.Err()
	}

	// 增加关注数
	err = h.relationNumDao.ModifyFollowingNumByTx(ctx, tx, req.UserId, 1)
	if err != nil {
		tx.Rollback()
		logger.Error("h.relationNumDao.ModifyFollowingNumByTx error", logger.Err(err), logger.Any("req", req), middleware.GCtxRequestIDField(c))
		return nil, ecode.InternalServerError.Err()
	}

	// 增加粉丝数
	err = h.relationNumDao.ModifyFollowerNumByTx(ctx, tx, req.FollowedUid, 1)
	if err != nil {
		tx.Rollback()
		logger.Error("h.relationNumDao.ModifyFollowerNumByTx error", logger.Err(err), logger.Any("req", req), middleware.GCtxRequestIDField(c))
		return nil, ecode.InternalServerError.Err()
	}

	err = tx.Commit().Error
	if err != nil {
		tx.Rollback()
		logger.Error("tx.Commit error", logger.Err(err), middleware.GCtxRequestIDField(c))
		return nil, ecode.InternalServerError.Err()
	}

	return &communityV1.FollowReply{}, nil
}

// Unfollow 取消关注
func (h *relationServiceHandler) Unfollow(ctx context.Context, req *communityV1.UnfollowRequest) (*communityV1.UnfollowReply, error) {
	c := ctx.(*gin.Context)
	err := req.Validate()
	if err != nil {
		logger.Warn("req.Validate error", logger.Err(err), logger.Any("req", req), middleware.GCtxRequestIDField(c))
		return nil, ecode.InvalidParams.Err()
	}

	// 判断是否取消关注自己
	if req.UserId == req.FollowedUid {
		logger.Warn("can not unfollow yourself", logger.Any("req", req), middleware.GCtxRequestIDField(c))
		return nil, ecode.ErrFollowSelfRelationService.Err()
	}

	// 判断是否已取消关注
	userFollowing, err := h.userFollowingDao.GetRelation(ctx, req.UserId, req.FollowedUid)
	if err != nil && !errors.Is(err, model.ErrRecordNotFound) {
		logger.Warn("h.userFollowingDao.GetRelation error", logger.Err(err), logger.Any("req", req), middleware.GCtxRequestIDField(c))
		return nil, ecode.InternalServerError.Err()
	}
	if userFollowing != nil && userFollowing.Status == followStatusNot {
		return &communityV1.UnfollowReply{}, nil
	}

	db := model.GetDB()
	tx := db.Begin()
	if tx.Error != nil {
		logger.Error("tx error", logger.Err(err), middleware.GCtxRequestIDField(c))
		return nil, ecode.InternalServerError.Err()
	}
	defer func() {
		if r := recover(); r != nil {
			tx.Rollback()
		}
	}()

	// 取消关注
	err = h.userFollowingDao.UpdateStatusByTx(ctx, tx, &model.UserFollowing{
		UserID:      req.UserId,
		FollowedUid: req.FollowedUid,
		Status:      followStatusNot,
	})
	if err != nil {
		tx.Rollback()
		logger.Error("h.userFollowingDao.CreateByTx error", logger.Err(err), logger.Any("req", req), middleware.GCtxRequestIDField(c))
		return nil, ecode.InternalServerError.Err()
	}

	// 取消粉丝
	err = h.userFollowerDao.UpdateStatusByTx(ctx, tx, &model.UserFollower{
		UserID:      req.FollowedUid,
		FollowerUid: req.UserId,
		Status:      followStatusNot,
	})
	if err != nil {
		tx.Rollback()
		logger.Error("h.userFollowingDao.CreateByTx error", logger.Err(err), logger.Any("req", req), middleware.GCtxRequestIDField(c))
		return nil, ecode.InternalServerError.Err()
	}

	// 减少关注数
	err = h.relationNumDao.ModifyFollowingNumByTx(ctx, tx, req.UserId, -1)
	if err != nil {
		tx.Rollback()
		logger.Error("h.relationNumDao.ModifyFollowingNumByTx error", logger.Err(err), logger.Any("req", req), middleware.GCtxRequestIDField(c))
		return nil, ecode.InternalServerError.Err()
	}

	// 减少粉丝数
	err = h.relationNumDao.ModifyFollowerNumByTx(ctx, tx, req.FollowedUid, -1)
	if err != nil {
		tx.Rollback()
		logger.Error("h.relationNumDao.ModifyFollowerNumByTx error", logger.Err(err), logger.Any("req", req), middleware.GCtxRequestIDField(c))
		return nil, ecode.InternalServerError.Err()
	}

	err = tx.Commit().Error
	if err != nil {
		tx.Rollback()
		logger.Error("tx.Commit error", logger.Err(err), middleware.GCtxRequestIDField(c))
		return nil, ecode.InternalServerError.Err()
	}

	return &communityV1.UnfollowReply{}, nil
}

// ListFollowing 关注列表
func (h *relationServiceHandler) ListFollowing(ctx context.Context, req *communityV1.ListFollowingRequest) (*communityV1.ListFollowingReply, error) {
	c := ctx.(*gin.Context)
	err := req.Validate()
	if err != nil {
		logger.Warn("req.Validate error", logger.Err(err), logger.Any("req", req), middleware.GCtxRequestIDField(c))
		return nil, ecode.InvalidParams.Err()
	}

	records, total, err := h.userFollowingDao.GetByColumns(ctx, &query.Params{
		Page: int(req.Page),
		Size: int(req.Limit),
		Sort: "-followed_uid",
		Columns: []query.Column{
			{
				Name:  "user_id",
				Value: req.UserId,
			},
			{
				Name:  "status",
				Value: followStatusDone,
			},
		},
	})
	if err != nil {
		logger.Error("h.userFollowingDao.GetByColumns error", logger.Err(err), logger.Any("req", req), middleware.GCtxRequestIDField(c))
		return nil, ecode.InternalServerError.Err()
	}

	followedUids := []uint64{}
	for _, record := range records {
		followedUids = append(followedUids, record.FollowedUid)
	}

	return &communityV1.ListFollowingReply{
		Total:        total,
		FollowedUids: followedUids,
	}, nil
}

// ListFollower 粉丝列表
func (h *relationServiceHandler) ListFollower(ctx context.Context, req *communityV1.ListFollowerRequest) (*communityV1.ListFollowerReply, error) {
	c := ctx.(*gin.Context)
	err := req.Validate()
	if err != nil {
		logger.Warn("req.Validate error", logger.Err(err), logger.Any("req", req), middleware.GCtxRequestIDField(c))
		return nil, ecode.InvalidParams.Err()
	}

	records, total, err := h.userFollowerDao.GetByColumns(ctx, &query.Params{
		Page: int(req.Page),
		Size: int(req.Limit),
		Sort: "-follower_uid",
		Columns: []query.Column{
			{
				Name:  "user_id",
				Value: req.UserId,
			},
			{
				Name:  "status",
				Value: followStatusDone,
			},
		},
	})
	if err != nil {
		logger.Error("h.userFollowerDao.GetByColumns error", logger.Err(err), logger.Any("req", req), middleware.GCtxRequestIDField(c))
		return nil, ecode.InternalServerError.Err()
	}

	followerUids := []uint64{}
	for _, record := range records {
		followerUids = append(followerUids, record.FollowerUid)
	}

	return &communityV1.ListFollowerReply{
		Total:        total,
		FollowerUids: followerUids,
	}, nil
}

// BatchGetRelation 批量获取关注关系，a和b,c,d的关注状态
func (h *relationServiceHandler) BatchGetRelation(ctx context.Context, req *communityV1.BatchGetRelationRequest) (*communityV1.BatchGetRelationReply, error) {
	c := ctx.(*gin.Context)
	err := req.Validate()
	if err != nil {
		logger.Warn("req.Validate error", logger.Err(err), logger.Any("req", req), middleware.GCtxRequestIDField(c))
		return nil, ecode.InvalidParams.Err()
	}

	records, err := h.userFollowingDao.BatchGetUserFollowing(ctx, req.UserId, req.Uids)
	if err != nil {
		logger.Error("h.userFollowingDao.BatchGetUserFollowing error", logger.Err(err), logger.Any("req", req), middleware.GCtxRequestIDField(c))
		return nil, ecode.InternalServerError.Err()
	}

	result := make(map[uint64]int32, len(req.Uids))
	for _, record := range records {
		result[record.FollowedUid] = int32(record.Status)
	}

	for _, uid := range req.Uids {
		if uid == req.UserId {
			continue
		}
		if _, ok := result[uid]; !ok {
			result[uid] = followStatusNot
		}
	}

	return &communityV1.BatchGetRelationReply{
		Result: result,
	}, nil
}
