// Code generated by https://github.com/zhufuyi/sponge

package ecode

import (
	"github.com/zhufuyi/sponge/pkg/errcode"
)

// inventory business-level rpc error codes.
// the _inventoryNO value range is 1~100, if the same number appears, it will cause a failure to start the service.
var (
	_inventoryNO       = 61
	_inventoryName     = "inventory"
	_inventoryBaseCode = errcode.RCode(_inventoryNO)

	StatusGetByIDInventory   = errcode.NewRPCStatus(_inventoryBaseCode+1, "failed to GetByID "+_inventoryName)
	// error codes are globally unique, adding 1 to the previous error code
)

