// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/inventory/v1/inventory.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetByIDRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetByIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetByIDRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetByIDRequestMultiError,
// or nil if none found.
func (m *GetByIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetByIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() < 1 {
		err := GetByIDRequestValidationError{
			field:  "Id",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetByIDRequestMultiError(errors)
	}

	return nil
}

// GetByIDRequestMultiError is an error wrapping multiple validation errors
// returned by GetByIDRequest.ValidateAll() if the designated constraints
// aren't met.
type GetByIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetByIDRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetByIDRequestMultiError) AllErrors() []error { return m }

// GetByIDRequestValidationError is the validation error returned by
// GetByIDRequest.Validate if the designated constraints aren't met.
type GetByIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetByIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetByIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetByIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetByIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetByIDRequestValidationError) ErrorName() string { return "GetByIDRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetByIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetByIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetByIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetByIDRequestValidationError{}

// Validate checks the field values on InventoryDetail with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *InventoryDetail) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on InventoryDetail with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// InventoryDetailMultiError, or nil if none found.
func (m *InventoryDetail) ValidateAll() error {
	return m.validate(true)
}

func (m *InventoryDetail) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Num

	// no validation rules for SoldNum

	if len(errors) > 0 {
		return InventoryDetailMultiError(errors)
	}

	return nil
}

// InventoryDetailMultiError is an error wrapping multiple validation errors
// returned by InventoryDetail.ValidateAll() if the designated constraints
// aren't met.
type InventoryDetailMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InventoryDetailMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InventoryDetailMultiError) AllErrors() []error { return m }

// InventoryDetailValidationError is the validation error returned by
// InventoryDetail.Validate if the designated constraints aren't met.
type InventoryDetailValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InventoryDetailValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InventoryDetailValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InventoryDetailValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InventoryDetailValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InventoryDetailValidationError) ErrorName() string { return "InventoryDetailValidationError" }

// Error satisfies the builtin error interface
func (e InventoryDetailValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInventoryDetail.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InventoryDetailValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InventoryDetailValidationError{}

// Validate checks the field values on GetByIDReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetByIDReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetByIDReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetByIDReplyMultiError, or
// nil if none found.
func (m *GetByIDReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetByIDReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetInventoryDetail()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetByIDReplyValidationError{
					field:  "InventoryDetail",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetByIDReplyValidationError{
					field:  "InventoryDetail",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetInventoryDetail()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetByIDReplyValidationError{
				field:  "InventoryDetail",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetByIDReplyMultiError(errors)
	}

	return nil
}

// GetByIDReplyMultiError is an error wrapping multiple validation errors
// returned by GetByIDReply.ValidateAll() if the designated constraints aren't met.
type GetByIDReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetByIDReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetByIDReplyMultiError) AllErrors() []error { return m }

// GetByIDReplyValidationError is the validation error returned by
// GetByIDReply.Validate if the designated constraints aren't met.
type GetByIDReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetByIDReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetByIDReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetByIDReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetByIDReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetByIDReplyValidationError) ErrorName() string { return "GetByIDReplyValidationError" }

// Error satisfies the builtin error interface
func (e GetByIDReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetByIDReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetByIDReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetByIDReplyValidationError{}
