// Code generated by https://github.com/zhufuyi/sponge

package routers

import (
	"context"

	community_gwV1 "community_gw/api/community_gw/v1"
	"community_gw/internal/service"

	"github.com/zhufuyi/sponge/pkg/gin/middleware"
	"github.com/zhufuyi/sponge/pkg/logger"

	"github.com/gin-gonic/gin"
	"google.golang.org/grpc/metadata"
)

func init() {
	allMiddlewareFns = append(allMiddlewareFns, func(c *middlewareConfig) {
		likeServiceMiddlewares(c)
	})

	allRouteFns = append(allRouteFns,
		func(r *gin.Engine, groupPathMiddlewares map[string][]gin.HandlerFunc, singlePathMiddlewares map[string][]gin.HandlerFunc) {
			likeServiceRouter(r, groupPathMiddlewares, singlePathMiddlewares, service.NewLikeServiceClient())
		})
}

func likeServiceRouter(
	r *gin.Engine,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iService community_gwV1.LikeServiceLogicer) {
	ctxFn := func(c *gin.Context) context.Context {
		md := metadata.New(map[string]string{
			// set metadata to be passed from http to rpc
			middleware.ContextRequestIDKey: middleware.GCtxRequestID(c), // request_id
			//middleware.HeaderAuthorizationKey: c.GetHeader(middleware.HeaderAuthorizationKey),  // authorization
		})
		return metadata.NewOutgoingContext(c.Request.Context(), md)
	}

	community_gwV1.RegisterLikeServiceRouter(
		r,
		groupPathMiddlewares,
		singlePathMiddlewares,
		iService,
		community_gwV1.WithLikeServiceRPCResponse(),
		community_gwV1.WithLikeServiceLogger(logger.Get()),
		community_gwV1.WithLikeServiceRPCStatusToHTTPCode(
		// Set some error codes to standard http return codes,
		// by default there is already ecode.StatusInternalServerError and ecode.StatusServiceUnavailable
		// example:
		// 	ecode.StatusUnimplemented, ecode.StatusAborted,
		),
		community_gwV1.WithLikeServiceWrapCtx(ctxFn),
	)
}

// you can set the middleware of a route group, or set the middleware of a single route,
// or you can mix them, pay attention to the duplication of middleware when mixing them,
// it is recommended to set the middleware of a single route in preference
func likeServiceMiddlewares(c *middlewareConfig) {
	// set up group route middleware, group path is left prefix rules,
	// if the left prefix is hit, the middleware will take effect, e.g. group route is /api/v1, route /api/v1/likeService/:id  will take effect
	c.setGroupPath("/api/v1/like", middleware.Auth(middleware.WithVerify(verify)))

	// set up single route middleware, just uncomment the code and fill in the middlewares, nothing else needs to be changed
	//c.setSinglePath("POST", "/api/v1/like", middleware.Auth())
	//c.setSinglePath("POST", "/api/v1/like/delete", middleware.Auth())
	//c.setSinglePath("POST", "/api/v1/like/post/list", middleware.Auth())
	//c.setSinglePath("POST", "/api/v1/like/comment/list", middleware.Auth())
}
